name: viperdev
channels:
  - conda-forge
dependencies:
# hostess dependencies
  - python>=3.9
  - boto3
  - cytoolz
  - dill
  - dustgoggles
  - more-itertools
  - pandas
  - postgis
  - postgresql
  - pyyaml
  - protobuf
  - psutil
  - pympler
  - python-magic
  - requests
  - rich
  - fabric
  - invoke
  - textual
  - fire
# dependencies for parquet
  - pyarrow
# thumbnails
  # `imageio` and `pillow` 10.1.0 have a compatibility issue
  - pillow==10.0.1
# dependencies for the visintent application
  - django
# dependencies for components of vipersci used by the orchestrator
  - genshi
  - psycopg2
  - scikit-image
  - sqlalchemy
  - tifftools
# dependencies for components of vipersci used by visintent
  - geoalchemy2
# dependencies for yamcs & dev stuff
  - beautifulsoup4
  - gunicorn
  - jupyter
  - ipython
  - pip
# yamcs-client wants to install a lower version that is incompatible with
# hostess, so don't add it to the environment file! (pip install yamcs-client --no-dependencies)
  - pip:
      - google