site_name: VIPER VIS Orchestrator
site_description: documentation for viper vis orchestrator https://github.com/MillionConcepts/viper-vis-orchestrator
theme:
  name: material
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          filters: []
          show_signature_annotations: true

nav:
  - 'index.md'
  - License: 'LICENSE.md'
  - API Reference: 'orchestrator_api.md'
