site_name: VIPER VIS Orchestrator
site_description: documentation for viper vis orchestrator https://github.com/MillionConcepts/viper-vis-orchestrator
theme:
  name: readthedocs
plugins:
- search
- mkdocstrings

nav:
  - 'index.md'
  - License: 'LICENSE.md'
  - API Reference: 'orchestrator_api.md'
